//! Patch template generation — builds the install script and gnx.rs tool stub
//! from the live inventory of registered MCP tools.

use graph_nexus_core::GnxError;
use graph_nexus_mcp::registry::GnxMcpTool;

pub(super) fn collect_gnx_tools() -> Vec<&'static GnxMcpTool> {
    inventory::iter::<GnxMcpTool>().collect()
}

/// Count `impl Tool for ` occurrences in the generated gnx.rs content.
pub(super) fn count_tools_in_file(content: &str) -> usize {
    content.matches("impl Tool for ").count()
}

/// Build the shell install script that patches a codex-rs checkout.
pub(super) fn build_install_sh(tools: &[&'static GnxMcpTool]) -> String {
    let tool_count = tools.len();
    format!(
        r#"#!/usr/bin/env sh
# AUTO-GENERATED by graph-nexus-cli codex_native patch generator.
# gnx-integration-marker-v1
# tools_count: {tool_count}
#
# Run from the root of your openai/codex fork:
#   sh codex-cli-install.sh
set -e

[ -f "codex-rs/core/Cargo.toml" ] || {{ echo "Error: run from the codex-rs repo root (expected codex-rs/core/Cargo.toml)"; exit 1; }}

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Append gnx dependencies to Cargo.toml only once.
if grep -q "graph-nexus-cli" codex-rs/core/Cargo.toml; then
    echo "gnx deps already present in codex-rs/core/Cargo.toml — skipping."
else
    cat >> codex-rs/core/Cargo.toml <<'DEPS'

# gnx-integration-marker-v1
graph-nexus-cli = {{ git = "https://github.com/coseto6125/graph-nexus", branch = "main" }}
graph-nexus-mcp = {{ git = "https://github.com/coseto6125/graph-nexus", branch = "main" }}
graph-nexus-core = {{ git = "https://github.com/coseto6125/graph-nexus", branch = "main" }}
DEPS
    echo "Added gnx deps to codex-rs/core/Cargo.toml."
fi

# Copy the generated gnx.rs Tool impl file.
cp "$SCRIPT_DIR/gnx.rs" codex-rs/core/src/tools/gnx.rs
echo "Copied gnx.rs to codex-rs/core/src/tools/gnx.rs."

# Register the gnx module in tools/mod.rs if not already present.
if grep -q "pub mod gnx;" codex-rs/core/src/tools/mod.rs; then
    echo "pub mod gnx; already present in tools/mod.rs — skipping."
else
    echo "pub mod gnx;" >> codex-rs/core/src/tools/mod.rs
    echo "Registered gnx module in codex-rs/core/src/tools/mod.rs."
fi

echo ""
echo "Done. Now run: cargo build -p codex-core"
echo "Your codex-cli binary will expose {tool_count} gnx_* tools natively (zero IPC)."
"#
    )
}

/// Build the gnx.rs file content with one `impl Tool for` block per registered tool.
pub(super) fn build_gnx_rs(tools: &[&'static GnxMcpTool]) -> Result<String, GnxError> {
    let tool_count = tools.len();

    let mut out = format!(
        r#"//! gnx integration tools. AUTO-GENERATED by graph-nexus-cli's
//! codex_native patch generator.
//!
//! gnx-integration-marker-v1
//! tools_count: {tool_count}
//!
// ┌─────────────────────────────────────────────────────────────────┐
// │ NOTE: codex-rs's Tool trait API may have shifted since gnx      │
// │ generated this file. If `cargo build` fails:                    │
// │   1. Check codex-rs/core/src/tools/mod.rs for the actual Tool  │
// │      trait method signatures.                                   │
// │   2. Adjust the impl blocks below accordingly.                  │
// │   3. The graph-nexus-cli::run_inner calls themselves are        │
// │      stable; only the wrapping Tool impl shape may differ.      │
// └─────────────────────────────────────────────────────────────────┘

// Adapt this import to match the actual codex-rs Tool trait path.
// Common locations: codex_core::tools::Tool, codex_core::protocol::Tool
use codex_core::tools::{{Tool, ToolResult}};
use graph_nexus_mcp::registry::{{GnxMcpTool, EngineRef}};
use serde_json::Value;

/// Shared helper: load a singleton Engine from the default graph.bin path.
fn load_engine() -> Result<impl EngineRef, Box<dyn std::error::Error + Send + Sync>> {{
    // Adjust the graph path to match your codex-rs workspace layout.
    let graph_path = std::path::PathBuf::from(".gitnexus-rs/graph.bin");
    let engine = graph_nexus_cli::engine::Engine::load(&graph_path)?;
    Ok(engine)
}}

"#
    );

    // Sort tools by name for stable output.
    let mut sorted: Vec<&GnxMcpTool> = tools.to_vec();
    sorted.sort_by_key(|t| (t.name)());

    for tool in &sorted {
        let tool_name = (tool.name)();
        let description = (tool.description)();
        let schema_json = serde_json::to_string_pretty(&(tool.schema)())
            .map_err(|e| GnxError::Serialization(format!("schema serialization: {e}")))?;

        // Derive a valid Rust struct name from the tool name.
        // "gnx_context" → "GnxContext"
        let struct_name = to_pascal_case(tool_name);

        out.push_str(&format!(
            r#"/// {description}
pub struct {struct_name};

impl Tool for {struct_name} {{
    fn name(&self) -> &str {{
        "{tool_name}"
    }}

    fn description(&self) -> &str {{
        "{description}"
    }}

    fn schema(&self) -> serde_json::Value {{
        // JSON Schema for arguments accepted by this tool.
        serde_json::json!({schema_json})
    }}

    async fn execute(&self, args: Value) -> Result<ToolResult, Box<dyn std::error::Error + Send + Sync>> {{
        let engine = load_engine()?;
        // Route to the registered inventory handler (in-process, zero IPC).
        let handler = inventory::iter::<GnxMcpTool>()
            .find(|t| (t.name)() == "{tool_name}")
            .expect("gnx tool not found in inventory — this is a bug");
        let result = (handler.handler)(args, &engine)?;
        Ok(ToolResult::text(result.to_string()))
    }}
}}

"#
        ));
    }

    Ok(out)
}

/// Convert a snake_case identifier to PascalCase.
/// "gnx_context" → "GnxContext", "gnx_multi_query" → "GnxMultiQuery"
fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .filter(|seg| !seg.is_empty())
        .map(|seg| {
            let mut c = seg.chars();
            match c.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::to_pascal_case;

    #[test]
    fn pascal_case_single_segment() {
        assert_eq!(to_pascal_case("context"), "Context");
    }

    #[test]
    fn pascal_case_gnx_prefix() {
        assert_eq!(to_pascal_case("gnx_context"), "GnxContext");
    }

    #[test]
    fn pascal_case_multi_segment() {
        assert_eq!(to_pascal_case("gnx_multi_query"), "GnxMultiQuery");
    }

    #[test]
    fn pascal_case_detect_changes() {
        assert_eq!(to_pascal_case("gnx_detect_changes"), "GnxDetectChanges");
    }
}
