pub mod admin;
pub mod auto_ensure;
pub mod build;
pub mod background;
pub use background::flock_preamble;
pub mod commands;
pub mod commit_lookup;
pub mod config_parser;
pub mod engine;
pub mod git;
pub mod git_state;
pub mod graph_path;
pub mod hint;
pub mod output;
pub mod parse_cache;
pub mod peer;
pub mod reanalyze;
pub mod repo_identity;
pub mod repo_selector;
pub mod search;
pub mod session;

pub(crate) const CGN_IGNORE_FILE: &str = ".cgnignore";
