//! Per-language stdlib/keyword denylists for `gnx scan --filter-stdlib`.
//!
//! `gnx scan` walks every identifier in a file and flags those that don't
//! resolve to a workspace symbol. Without filtering, the output is dominated
//! by stdlib types, language keywords, and well-known package roots — noise
//! that masks the real signal (typos / dangling references to project code).
//!
//! Empirically (against `.sample_repo/`): turning on `--filter-stdlib` cuts
//! noise by 43%–100% depending on language. Each bucket below is a small,
//! curated list; `linear contains` on `&[&str]` is faster than a `HashSet`
//! at these sizes and keeps the data layout cache-friendly.

use std::path::Path;

/// Return the stdlib denylist that applies to `ext`. Empty slice for
/// unsupported extensions — caller can short-circuit when filtering is on
/// but no list is available.
pub fn stdlib_denylist_for(ext: &str) -> &'static [&'static str] {
    match ext {
        "py" | "pyi" => PYTHON,
        "ts" | "tsx" | "js" | "jsx" | "mjs" | "cjs" => JS_TS,
        "rs" => RUST,
        "go" => GO,
        "java" | "kt" | "kts" => JVM,
        "cs" => CSHARP,
        "rb" => RUBY,
        "swift" => SWIFT,
        "c" | "h" | "cpp" | "hpp" | "cc" | "hh" | "cxx" | "hxx" => C_CPP,
        "dart" => DART,
        "php" => PHP,
        _ => &[],
    }
}

/// True if `name` is stdlib noise for the given extension. Composes a fast
/// `&[&str]` lookup with one structural rule (Python's `__dunder__` pattern)
/// that would otherwise blow up the static list.
pub fn is_stdlib_noise(name: &str, ext: &str) -> bool {
    // Python (and Cython-style stubs) dunder convention. Skip anything that
    // looks like `__name__` since these are language-provided attributes,
    // never project symbols a user would mistype.
    if matches!(ext, "py" | "pyi") && is_python_dunder(name) {
        return true;
    }
    stdlib_denylist_for(ext).contains(&name)
}

fn is_python_dunder(name: &str) -> bool {
    name.len() >= 5 && name.starts_with("__") && name.ends_with("__")
}

/// Drop entries whose `name` is stdlib noise for the file's extension.
/// Returns `(kept, dropped_count)` so the caller can report filtering
/// effort in the output payload.
pub fn filter_refs(refs: Vec<(String, usize)>, file_path: &Path) -> (Vec<(String, usize)>, usize) {
    let ext = file_path.extension().and_then(|s| s.to_str()).unwrap_or("");
    if ext.is_empty() {
        return (refs, 0);
    }
    let denylist = stdlib_denylist_for(ext);
    // `--filter-stdlib` for an extension we don't know about is a no-op
    // rather than an error — the user can still get value from any project
    // symbol matches even if we can't trim noise.
    if denylist.is_empty() && !matches!(ext, "py" | "pyi") {
        return (refs, 0);
    }
    let before = refs.len();
    let kept: Vec<(String, usize)> = refs
        .into_iter()
        .filter(|(name, _)| !is_stdlib_noise(name, ext))
        .collect();
    let dropped = before - kept.len();
    (kept, dropped)
}

// ─── Per-language denylists ─────────────────────────────────────────────────
//
// Each list covers: language keywords, primitive types, the most common
// stdlib types / module roots, and the handful of method names that appear
// on nearly every other line of idiomatic code. Domain-specific frameworks
// (Flask, Nest, Spring, …) are NOT included — those are exactly the symbols
// `gnx scan` should help users verify spelled correctly.

const PYTHON: &[&str] = &[
    // Reserved + literal builtins
    "True",
    "False",
    "None",
    "self",
    "cls",
    "pass",
    "lambda",
    "yield",
    "async",
    "await",
    "global",
    "nonlocal",
    "del",
    // Numeric / collection types
    "str",
    "int",
    "float",
    "bool",
    "bytes",
    "bytearray",
    "complex",
    "list",
    "dict",
    "set",
    "frozenset",
    "tuple",
    "object",
    "type",
    // Builtin functions
    "print",
    "len",
    "range",
    "enumerate",
    "zip",
    "map",
    "filter",
    "sorted",
    "reversed",
    "sum",
    "min",
    "max",
    "abs",
    "round",
    "pow",
    "divmod",
    "any",
    "all",
    "next",
    "iter",
    "open",
    "input",
    "id",
    "hash",
    "repr",
    "format",
    "ascii",
    "bin",
    "oct",
    "hex",
    "chr",
    "ord",
    "vars",
    "dir",
    "isinstance",
    "issubclass",
    "hasattr",
    "getattr",
    "setattr",
    "delattr",
    "globals",
    "locals",
    "callable",
    "classmethod",
    "staticmethod",
    "property",
    "super",
    "slice",
    "memoryview",
    "compile",
    "exec",
    "eval",
    // Exceptions
    "Exception",
    "BaseException",
    "ValueError",
    "TypeError",
    "KeyError",
    "IndexError",
    "AttributeError",
    "RuntimeError",
    "OSError",
    "IOError",
    "NotImplementedError",
    "StopIteration",
    "StopAsyncIteration",
    "ArithmeticError",
    "ZeroDivisionError",
    "OverflowError",
    // `typing` module surface (canonical names + aliases)
    "Any",
    "Callable",
    "ClassVar",
    "Collection",
    "TypeVar",
    "Optional",
    "Union",
    "List",
    "Dict",
    "Tuple",
    "Set",
    "FrozenSet",
    "Iterable",
    "Iterator",
    "Generator",
    "Awaitable",
    "AsyncIterator",
    "Generic",
    "Protocol",
    "Sequence",
    "Mapping",
    "MutableMapping",
    "Type",
    "Literal",
    "Final",
    "TypedDict",
    "NamedTuple",
    "NewType",
    "cast",
    "overload",
    "TYPE_CHECKING",
    // Common stdlib module roots
    "os",
    "sys",
    "json",
    "typing",
    "collections",
    "functools",
    "itertools",
    "re",
    "logging",
    "warnings",
    "weakref",
    "inspect",
    "dataclasses",
    "enum",
    "pathlib",
    "datetime",
    "time",
    "math",
    "random",
    "hashlib",
    "abc",
    "copy",
    "io",
    "uuid",
    "subprocess",
    "threading",
    "asyncio",
    "concurrent",
    "contextlib",
    "pickle",
    "base64",
    "struct",
    "socket",
    "urllib",
    "http",
    "email",
    "platform",
    "argparse",
    "tempfile",
    // Common methods on builtin types (string, list, dict, set)
    "append",
    "extend",
    "pop",
    "insert",
    "remove",
    "get",
    "keys",
    "values",
    "items",
    "update",
    "join",
    "split",
    "rsplit",
    "splitlines",
    "strip",
    "lstrip",
    "rstrip",
    "replace",
    "startswith",
    "endswith",
    "find",
    "rfind",
    "index",
    "count",
    "lower",
    "upper",
    "title",
    "capitalize",
    "encode",
    "decode",
    "add",
    "discard",
    "union",
    "intersection",
    "difference",
    "copy",
    "clear",
    "fromkeys",
    "setdefault",
];

const JS_TS: &[&str] = &[
    // Literals & control keywords
    "true",
    "false",
    "null",
    "undefined",
    "this",
    "void",
    "yield",
    // Primitive / structural types (TS)
    "any",
    "unknown",
    "never",
    "string",
    "number",
    "boolean",
    "object",
    "bigint",
    "symbol",
    // TS-only keywords
    "as",
    "is",
    "keyof",
    "typeof",
    "readonly",
    "infer",
    "abstract",
    "interface",
    "type",
    "enum",
    "namespace",
    "module",
    "declare",
    "implements",
    "satisfies",
    // Global objects & well-known types
    "console",
    "JSON",
    "Math",
    "Date",
    "Symbol",
    "Promise",
    "Error",
    "TypeError",
    "RangeError",
    "SyntaxError",
    "Map",
    "Set",
    "WeakMap",
    "WeakSet",
    "Array",
    "Object",
    "Number",
    "String",
    "Boolean",
    "RegExp",
    "Proxy",
    "Reflect",
    "NaN",
    "Infinity",
    "globalThis",
    "window",
    "document",
    "process",
    "Buffer",
    "BigInt",
    "ArrayBuffer",
    "Uint8Array",
    // Single-letter generic parameters (always type params)
    "T",
    "U",
    "K",
    "V",
    "R",
    "E",
    "P",
    "S",
    // Console / Promise / Array methods that dominate idiomatic code
    "log",
    "error",
    "warn",
    "info",
    "debug",
    "trace",
    "parse",
    "stringify",
    "push",
    "pop",
    "shift",
    "unshift",
    "slice",
    "splice",
    "concat",
    "join",
    "map",
    "filter",
    "reduce",
    "forEach",
    "find",
    "findIndex",
    "includes",
    "indexOf",
    "lastIndexOf",
    "length",
    "size",
    "then",
    "catch",
    "finally",
    "resolve",
    "reject",
    "all",
    "race",
    "allSettled",
    "any",
    "toString",
    "valueOf",
    "hasOwnProperty",
    "isArray",
    "keys",
    "values",
    "entries",
    "assign",
    "freeze",
    "isFrozen",
    "create",
    "defineProperty",
    "getOwnPropertyNames",
    "getPrototypeOf",
];

const RUST: &[&str] = &[
    // Stdlib module roots
    "std",
    "core",
    "alloc",
    "collections",
    "path",
    "process",
    "fs",
    "io",
    "sync",
    "cmp",
    "fmt",
    "mem",
    "ops",
    "iter",
    "str",
    "cell",
    "rc",
    "thread",
    "time",
    "env",
    "ffi",
    "marker",
    "ptr",
    "slice",
    "borrow",
    "convert",
    "default",
    "future",
    "hash",
    "num",
    // Stdlib types
    "String",
    "Vec",
    "Box",
    "Option",
    "Result",
    "Arc",
    "Mutex",
    "Rc",
    "RefCell",
    "Cell",
    "HashMap",
    "BTreeMap",
    "HashSet",
    "BTreeSet",
    "Path",
    "PathBuf",
    "Command",
    "Cow",
    "OsStr",
    "OsString",
    "File",
    "BufReader",
    "BufWriter",
    "Range",
    "RangeInclusive",
    // Variants
    "Ok",
    "Err",
    "Some",
    "None",
    // Traits + derive macros
    "Debug",
    "Clone",
    "Default",
    "Send",
    "Sync",
    "Copy",
    "Eq",
    "PartialEq",
    "Hash",
    "Ord",
    "PartialOrd",
    "From",
    "Into",
    "TryFrom",
    "TryInto",
    "AsRef",
    "AsMut",
    "Deref",
    "DerefMut",
    "Drop",
    "Iterator",
    "IntoIterator",
    "FnOnce",
    "FnMut",
    "Fn",
    "Sized",
    "Display",
    "Write",
    "Read",
    "Seek",
    "Args",
    "Subcommand",
    "Parser",
    "ValueEnum",
    // Builtin macros
    "assert",
    "assert_eq",
    "assert_ne",
    "debug_assert",
    "debug_assert_eq",
    "cfg",
    "derive",
    "vec",
    "format",
    "println",
    "eprintln",
    "print",
    "eprint",
    "dbg",
    "todo",
    "unimplemented",
    "unreachable",
    "panic",
    "include_str",
    "include_bytes",
    "concat",
    "stringify",
    "env",
    "matches",
    // Pervasive method names on Option/Result/Vec/Iterator/Display
    "unwrap",
    "unwrap_or",
    "unwrap_or_else",
    "unwrap_or_default",
    "expect",
    "to_string",
    "to_owned",
    "as_str",
    "as_ref",
    "as_mut",
    "as_deref",
    "iter",
    "into_iter",
    "iter_mut",
    "map",
    "map_err",
    "and_then",
    "or_else",
    "collect",
    "push",
    "pop",
    "insert",
    "remove",
    "clone",
    "len",
    "is_empty",
    "entry",
    "or_insert",
    "or_insert_with",
    "keys",
    "values",
    "sum",
    "find",
    "filter",
    "fold",
    "reduce",
    "take",
    "skip",
    "chain",
    "zip",
    "enumerate",
    "rev",
    "min",
    "max",
    "count",
    "contains",
    "join",
    "parent",
    "extend",
    "starts_with",
    "ends_with",
    "trim",
    "split",
    "splitn",
];

const GO: &[&str] = &[
    // Keywords
    "break",
    "default",
    "func",
    "interface",
    "select",
    "case",
    "defer",
    "go",
    "map",
    "struct",
    "chan",
    "else",
    "goto",
    "package",
    "switch",
    "const",
    "fallthrough",
    "if",
    "range",
    "type",
    "continue",
    "for",
    "import",
    "return",
    "var",
    // Predeclared identifiers
    "true",
    "false",
    "nil",
    "iota",
    "bool",
    "byte",
    "rune",
    "string",
    "error",
    "uintptr",
    "int",
    "int8",
    "int16",
    "int32",
    "int64",
    "uint",
    "uint8",
    "uint16",
    "uint32",
    "uint64",
    "float32",
    "float64",
    "complex64",
    "complex128",
    // Builtin functions
    "len",
    "cap",
    "make",
    "new",
    "append",
    "copy",
    "delete",
    "panic",
    "recover",
    "print",
    "println",
    "close",
    // Common stdlib package roots
    "fmt",
    "os",
    "io",
    "strings",
    "bytes",
    "errors",
    "context",
    "sync",
    "time",
    "net",
    "http",
    "encoding",
    "json",
    "log",
    "math",
    "sort",
    "strconv",
    "regexp",
    "bufio",
    "path",
    "filepath",
    "reflect",
    "runtime",
];

const JVM: &[&str] = &[
    // Java primitives
    "int",
    "long",
    "byte",
    "short",
    "float",
    "double",
    "boolean",
    "char",
    "void",
    "null",
    "true",
    "false",
    "this",
    "super",
    // Modifiers / reserved
    "public",
    "private",
    "protected",
    "static",
    "final",
    "abstract",
    "synchronized",
    "volatile",
    "transient",
    "native",
    "strictfp",
    "class",
    "interface",
    "enum",
    "extends",
    "implements",
    "import",
    "package",
    "return",
    "if",
    "else",
    "for",
    "while",
    "do",
    "switch",
    "case",
    "break",
    "continue",
    "throw",
    "throws",
    "try",
    "catch",
    "finally",
    "new",
    "instanceof",
    "default",
    // Stdlib package roots
    "java",
    "javax",
    "kotlin",
    "kotlinx",
    "com",
    "org",
    // Common stdlib types
    "String",
    "Object",
    "Integer",
    "Long",
    "Boolean",
    "Number",
    "Double",
    "Float",
    "Byte",
    "Short",
    "Character",
    "Comparable",
    "Iterable",
    "List",
    "ArrayList",
    "LinkedList",
    "Map",
    "HashMap",
    "TreeMap",
    "LinkedHashMap",
    "Set",
    "HashSet",
    "TreeSet",
    "LinkedHashSet",
    "Queue",
    "Deque",
    "ArrayDeque",
    "Optional",
    "Stream",
    "Collectors",
    "Collection",
    "Collections",
    "Arrays",
    "System",
    "Math",
    "StringBuilder",
    "StringBuffer",
    "Iterator",
    "Iterable",
    "Comparable",
    "Comparator",
    "Runnable",
    "Thread",
    "Exception",
    "RuntimeException",
    "Throwable",
    // Common annotations
    "Override",
    "Nullable",
    "NonNull",
    "Deprecated",
    "SuppressWarnings",
    "FunctionalInterface",
    "SafeVarargs",
    "Generated",
    // Pervasive methods
    "toString",
    "hashCode",
    "equals",
    "compareTo",
    "valueOf",
    "getClass",
    "intValue",
    "longValue",
    "doubleValue",
    "size",
    "isEmpty",
    "add",
    "remove",
    "contains",
    "get",
    "put",
    "clear",
    "iterator",
    "stream",
    // Kotlin specifics
    "fun",
    "val",
    "var",
    "object",
    "data",
    "sealed",
    "open",
    "inner",
    "companion",
    "init",
    "lateinit",
    "by",
    "in",
    "out",
    "Unit",
    "Nothing",
    "Any",
    "let",
    "apply",
    "also",
    "run",
    "with",
    "use",
];

const CSHARP: &[&str] = &[
    // Primitives + special
    "int",
    "long",
    "byte",
    "short",
    "float",
    "double",
    "bool",
    "char",
    "void",
    "string",
    "object",
    "var",
    "dynamic",
    "decimal",
    "sbyte",
    "uint",
    "ulong",
    "ushort",
    "null",
    "true",
    "false",
    "this",
    "base",
    // Reserved
    "public",
    "private",
    "protected",
    "internal",
    "static",
    "readonly",
    "const",
    "abstract",
    "sealed",
    "virtual",
    "override",
    "partial",
    "async",
    "await",
    "namespace",
    "using",
    "class",
    "struct",
    "interface",
    "enum",
    "delegate",
    "record",
    "return",
    "if",
    "else",
    "for",
    "while",
    "do",
    "foreach",
    "in",
    "switch",
    "case",
    "break",
    "continue",
    "throw",
    "try",
    "catch",
    "finally",
    "new",
    "is",
    "as",
    "ref",
    "out",
    "params",
    // Stdlib roots
    "System",
    "Collections",
    "Generic",
    "Linq",
    "IO",
    "Threading",
    "Tasks",
    "Text",
    "RegularExpressions",
    "Globalization",
    "Diagnostics",
    // Common types
    "List",
    "Dictionary",
    "HashSet",
    "Queue",
    "Stack",
    "IEnumerable",
    "IList",
    "ICollection",
    "IDictionary",
    "IComparer",
    "Func",
    "Action",
    "Task",
    "String",
    "Object",
    "Exception",
    "ArgumentException",
    "NullReferenceException",
    "InvalidOperationException",
    "Nullable",
    // Methods
    "ToString",
    "GetHashCode",
    "Equals",
    "GetType",
    "Add",
    "Remove",
    "Clear",
    "Count",
    "Length",
    "Contains",
    "TryGetValue",
    "FirstOrDefault",
    "Where",
    "Select",
    "OrderBy",
    "GroupBy",
    "ToList",
    "ToArray",
    "ToDictionary",
];

const RUBY: &[&str] = &[
    // Keywords
    "def",
    "end",
    "class",
    "module",
    "if",
    "elsif",
    "else",
    "unless",
    "then",
    "while",
    "until",
    "for",
    "in",
    "do",
    "return",
    "yield",
    "begin",
    "rescue",
    "ensure",
    "raise",
    "nil",
    "true",
    "false",
    "self",
    "super",
    "and",
    "or",
    "not",
    "case",
    "when",
    "break",
    "next",
    "redo",
    "retry",
    "defined?",
    "BEGIN",
    "END",
    "__FILE__",
    "__LINE__",
    // Core classes
    "String",
    "Integer",
    "Float",
    "Numeric",
    "Array",
    "Hash",
    "Symbol",
    "Range",
    "Class",
    "Module",
    "Object",
    "Kernel",
    "IO",
    "File",
    "Dir",
    "Time",
    "Date",
    "Regexp",
    "Proc",
    "Lambda",
    "Enumerable",
    "Comparable",
    "Exception",
    "StandardError",
    "RuntimeError",
    "ArgumentError",
    "TypeError",
    "NameError",
    "NoMethodError",
    // Pervasive methods
    "each",
    "each_with_index",
    "each_pair",
    "map",
    "select",
    "reject",
    "reduce",
    "inject",
    "find",
    "detect",
    "any?",
    "all?",
    "none?",
    "one?",
    "push",
    "pop",
    "shift",
    "unshift",
    "length",
    "size",
    "count",
    "include?",
    "empty?",
    "nil?",
    "to_s",
    "to_i",
    "to_f",
    "to_a",
    "to_h",
    "to_sym",
    "puts",
    "print",
    "p",
    "pp",
    "raise",
    "freeze",
    "frozen?",
    "respond_to?",
    "is_a?",
    "kind_of?",
    "send",
    "method",
    "methods",
    "instance_variable_get",
    "instance_variable_set",
    "attr_accessor",
    "attr_reader",
    "attr_writer",
    "require",
    "require_relative",
    "load",
];

const SWIFT: &[&str] = &[
    // Keywords
    "var",
    "let",
    "func",
    "class",
    "struct",
    "enum",
    "protocol",
    "extension",
    "init",
    "deinit",
    "subscript",
    "convenience",
    "required",
    "override",
    "open",
    "public",
    "internal",
    "fileprivate",
    "private",
    "static",
    "final",
    "lazy",
    "weak",
    "unowned",
    "mutating",
    "nonmutating",
    "return",
    "if",
    "else",
    "for",
    "while",
    "repeat",
    "switch",
    "case",
    "default",
    "break",
    "continue",
    "fallthrough",
    "guard",
    "throw",
    "throws",
    "rethrows",
    "try",
    "catch",
    "defer",
    "do",
    "where",
    "as",
    "is",
    "nil",
    "true",
    "false",
    "self",
    "Self",
    "super",
    "Any",
    "Type",
    "associatedtype",
    "typealias",
    "import",
    "in",
    "inout",
    // Standard types
    "Int",
    "Int8",
    "Int16",
    "Int32",
    "Int64",
    "UInt",
    "UInt8",
    "UInt16",
    "UInt32",
    "UInt64",
    "Double",
    "Float",
    "Bool",
    "String",
    "Character",
    "Array",
    "Dictionary",
    "Set",
    "Optional",
    "Range",
    "ClosedRange",
    "AnyObject",
    "AnyClass",
    "Result",
    "Error",
    "Equatable",
    "Hashable",
    "Comparable",
    "CustomStringConvertible",
    "Codable",
    "Encodable",
    "Decodable",
    "Sequence",
    "Collection",
    "Iterator",
    // Common methods + properties
    "append",
    "insert",
    "remove",
    "removeAll",
    "removeFirst",
    "removeLast",
    "count",
    "isEmpty",
    "first",
    "last",
    "map",
    "filter",
    "reduce",
    "compactMap",
    "flatMap",
    "contains",
    "sorted",
    "reversed",
    "forEach",
    "description",
    "rawValue",
    "hashValue",
    "min",
    "max",
];

const C_CPP: &[&str] = &[
    // Common to C + C++
    "int",
    "long",
    "short",
    "char",
    "float",
    "double",
    "void",
    "signed",
    "unsigned",
    "const",
    "static",
    "extern",
    "inline",
    "auto",
    "volatile",
    "register",
    "struct",
    "union",
    "enum",
    "typedef",
    "sizeof",
    "return",
    "if",
    "else",
    "for",
    "while",
    "do",
    "switch",
    "case",
    "break",
    "continue",
    "goto",
    "default",
    "NULL",
    // C++ specifics
    "bool",
    "true",
    "false",
    "this",
    "nullptr",
    "class",
    "namespace",
    "using",
    "public",
    "private",
    "protected",
    "virtual",
    "override",
    "final",
    "friend",
    "mutable",
    "explicit",
    "template",
    "typename",
    "throw",
    "try",
    "catch",
    "new",
    "delete",
    "operator",
    "typeid",
    "static_cast",
    "dynamic_cast",
    "const_cast",
    "reinterpret_cast",
    "decltype",
    "constexpr",
    "consteval",
    "concept",
    "requires",
    // Stdlib namespace + common types
    "std",
    "string",
    "wstring",
    "vector",
    "array",
    "map",
    "unordered_map",
    "set",
    "unordered_set",
    "list",
    "deque",
    "queue",
    "stack",
    "pair",
    "tuple",
    "unique_ptr",
    "shared_ptr",
    "weak_ptr",
    "optional",
    "variant",
    "any",
    "function",
    "iostream",
    "istream",
    "ostream",
    "cin",
    "cout",
    "cerr",
    "endl",
    // Pervasive methods
    "size",
    "empty",
    "push_back",
    "pop_back",
    "emplace_back",
    "begin",
    "end",
    "cbegin",
    "cend",
    "rbegin",
    "rend",
    "find",
    "insert",
    "erase",
    "clear",
    "at",
    "front",
    "back",
    "data",
    "resize",
    "reserve",
    "swap",
    "get",
    "release",
    "reset",
    "make_unique",
    "make_shared",
    "move",
    "forward",
];

const DART: &[&str] = &[
    // Built-in types
    "int",
    "double",
    "num",
    "bool",
    "String",
    "List",
    "Map",
    "Set",
    "Iterable",
    "dynamic",
    "void",
    "Object",
    "Future",
    "Stream",
    "Symbol",
    "Function",
    "Type",
    "Null",
    "Never",
    // Keywords
    "var",
    "final",
    "const",
    "late",
    "class",
    "abstract",
    "extends",
    "implements",
    "mixin",
    "with",
    "factory",
    "this",
    "super",
    "null",
    "true",
    "false",
    "await",
    "async",
    "sync",
    "yield",
    "return",
    "if",
    "else",
    "for",
    "while",
    "do",
    "switch",
    "case",
    "default",
    "break",
    "continue",
    "throw",
    "try",
    "catch",
    "on",
    "finally",
    "rethrow",
    "new",
    "is",
    "as",
    "in",
    "of",
    "covariant",
    "deferred",
    "external",
    "operator",
    "part",
    "library",
    "import",
    "export",
    "show",
    "hide",
    "typedef",
    "enum",
    "extension",
    // Pervasive methods
    "add",
    "addAll",
    "remove",
    "removeWhere",
    "removeLast",
    "removeAt",
    "length",
    "isEmpty",
    "isNotEmpty",
    "contains",
    "containsKey",
    "containsValue",
    "first",
    "last",
    "map",
    "where",
    "any",
    "every",
    "fold",
    "reduce",
    "forEach",
    "toList",
    "toSet",
    "toString",
    "noSuchMethod",
    "runtimeType",
    "hashCode",
];

const PHP: &[&str] = &[
    // Reserved keywords
    "function",
    "class",
    "interface",
    "trait",
    "extends",
    "implements",
    "abstract",
    "final",
    "public",
    "private",
    "protected",
    "static",
    "const",
    "namespace",
    "use",
    "return",
    "if",
    "else",
    "elseif",
    "endif",
    "for",
    "endfor",
    "foreach",
    "endforeach",
    "while",
    "endwhile",
    "do",
    "switch",
    "endswitch",
    "case",
    "default",
    "break",
    "continue",
    "throw",
    "try",
    "catch",
    "finally",
    "new",
    "instanceof",
    "null",
    "true",
    "false",
    "self",
    "parent",
    "global",
    "echo",
    "print",
    "include",
    "require",
    "include_once",
    "require_once",
    "as",
    // Superglobals (without the leading $ which scan strips)
    "_GET",
    "_POST",
    "_REQUEST",
    "_SESSION",
    "_COOKIE",
    "_SERVER",
    "_FILES",
    "_ENV",
    "GLOBALS",
    // Frequent builtin functions
    "array",
    "count",
    "sizeof",
    "is_array",
    "is_string",
    "is_int",
    "is_null",
    "isset",
    "empty",
    "unset",
    "strlen",
    "strpos",
    "strstr",
    "substr",
    "explode",
    "implode",
    "str_replace",
    "preg_match",
    "preg_replace",
    "var_dump",
    "print_r",
    "json_encode",
    "json_decode",
    "array_map",
    "array_filter",
    "array_reduce",
    "array_merge",
    "in_array",
    "array_keys",
    "array_values",
    "array_search",
    "sort",
    "ksort",
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn python_dunders_are_dropped() {
        for ext in ["py", "pyi"] {
            assert!(is_stdlib_noise("__init__", ext));
            assert!(is_stdlib_noise("__name__", ext));
            assert!(is_stdlib_noise("__doc__", ext));
            // `__x` (single leading) is NOT a dunder
            assert!(!is_stdlib_noise("__x", ext));
        }
        // Dunder pattern only fires for Python.
        assert!(!is_stdlib_noise("__name__", "rs"));
    }

    #[test]
    fn python_builtin_and_typing_caught() {
        for name in [
            "self",
            "cls",
            "list",
            "dict",
            "Any",
            "Callable",
            "Optional",
            "isinstance",
            "typing",
            "os",
            "json",
        ] {
            assert!(is_stdlib_noise(name, "py"), "{name} should be noise");
        }
        // Project symbol — must NOT be dropped
        assert!(!is_stdlib_noise("RouteCallable", "py"));
        assert!(!is_stdlib_noise("view_class", "py"));
    }

    #[test]
    fn js_ts_share_denylist_across_extensions() {
        for ext in ["ts", "tsx", "js", "jsx", "mjs", "cjs"] {
            assert!(is_stdlib_noise("console", ext));
            assert!(is_stdlib_noise("Promise", ext));
            assert!(is_stdlib_noise("T", ext));
            assert!(is_stdlib_noise("readonly", ext));
        }
        assert!(!is_stdlib_noise("SocketsContainer", "ts"));
    }

    #[test]
    fn rust_stdlib_caught() {
        assert!(is_stdlib_noise("std", "rs"));
        assert!(is_stdlib_noise("Vec", "rs"));
        assert!(is_stdlib_noise("Result", "rs"));
        assert!(is_stdlib_noise("Ok", "rs"));
        assert!(is_stdlib_noise("unwrap_or", "rs"));
        // Project struct/fn — must remain
        assert!(!is_stdlib_noise("ZeroCopyGraph", "rs"));
        assert!(!is_stdlib_noise("classify_framework_reason", "rs"));
    }

    #[test]
    fn go_predeclared_caught() {
        assert!(is_stdlib_noise("func", "go"));
        assert!(is_stdlib_noise("int", "go"));
        assert!(is_stdlib_noise("nil", "go"));
        assert!(is_stdlib_noise("len", "go"));
        assert!(is_stdlib_noise("fmt", "go"));
        assert!(!is_stdlib_noise("fetchOrder", "go"));
    }

    #[test]
    fn jvm_covers_java_and_kotlin() {
        for ext in ["java", "kt", "kts"] {
            assert!(is_stdlib_noise("String", ext));
            assert!(is_stdlib_noise("Override", ext));
            assert!(is_stdlib_noise("java", ext));
            assert!(is_stdlib_noise("HashMap", ext));
        }
        // Kotlin-only
        assert!(is_stdlib_noise("fun", "kt"));
        assert!(is_stdlib_noise("companion", "kt"));
        // Project class — must remain
        assert!(!is_stdlib_noise("UnsignedLong", "java"));
    }

    #[test]
    fn csharp_keywords_and_linq_caught() {
        assert!(is_stdlib_noise("var", "cs"));
        assert!(is_stdlib_noise("namespace", "cs"));
        assert!(is_stdlib_noise("List", "cs"));
        assert!(is_stdlib_noise("Where", "cs"));
        assert!(!is_stdlib_noise("CustomerService", "cs"));
    }

    #[test]
    fn ruby_keywords_and_core_caught() {
        assert!(is_stdlib_noise("def", "rb"));
        assert!(is_stdlib_noise("nil", "rb"));
        assert!(is_stdlib_noise("Hash", "rb"));
        assert!(is_stdlib_noise("each", "rb"));
        assert!(!is_stdlib_noise("ApplicationController", "rb"));
    }

    #[test]
    fn swift_keywords_and_types_caught() {
        assert!(is_stdlib_noise("func", "swift"));
        assert!(is_stdlib_noise("guard", "swift"));
        assert!(is_stdlib_noise("Optional", "swift"));
        assert!(is_stdlib_noise("Codable", "swift"));
        assert!(!is_stdlib_noise("ViewController", "swift"));
    }

    #[test]
    fn c_cpp_share_denylist() {
        for ext in ["c", "h", "cpp", "hpp", "cc", "hh", "cxx", "hxx"] {
            assert!(is_stdlib_noise("int", ext));
            assert!(is_stdlib_noise("const", ext));
            assert!(is_stdlib_noise("NULL", ext));
        }
        // C++-only — still caught (shared list is fine)
        assert!(is_stdlib_noise("nullptr", "cpp"));
        assert!(is_stdlib_noise("std", "cpp"));
        assert!(is_stdlib_noise("vector", "cpp"));
        assert!(!is_stdlib_noise("MyParser", "cpp"));
    }

    #[test]
    fn dart_keywords_and_types_caught() {
        assert!(is_stdlib_noise("late", "dart"));
        assert!(is_stdlib_noise("Future", "dart"));
        assert!(is_stdlib_noise("Stream", "dart"));
        assert!(!is_stdlib_noise("MyWidget", "dart"));
    }

    #[test]
    fn php_keywords_and_superglobals_caught() {
        assert!(is_stdlib_noise("function", "php"));
        assert!(is_stdlib_noise("namespace", "php"));
        assert!(is_stdlib_noise("_GET", "php"));
        assert!(is_stdlib_noise("isset", "php"));
        assert!(!is_stdlib_noise("UserModel", "php"));
    }

    #[test]
    fn unknown_extension_filters_nothing() {
        // The filter is a no-op for unsupported extensions — the user can
        // still see all unresolved refs, just without trimming.
        let refs = vec![("foo".into(), 1usize), ("bar".into(), 2usize)];
        let (kept, dropped) = filter_refs(refs, Path::new("file.unknown"));
        assert_eq!(kept.len(), 2);
        assert_eq!(dropped, 0);
    }

    #[test]
    fn filter_refs_drops_python_noise_and_keeps_project_names() {
        let refs = vec![
            ("self".into(), 1usize),
            ("ResponseReturnValue".into(), 2usize),
            ("Any".into(), 3usize),
            ("view_class".into(), 4usize),
            ("__init__".into(), 5usize),
            ("os".into(), 6usize),
        ];
        let (kept, dropped) = filter_refs(refs, Path::new("flask/views.py"));
        let names: Vec<&str> = kept.iter().map(|(n, _)| n.as_str()).collect();
        assert_eq!(names, vec!["ResponseReturnValue", "view_class"]);
        assert_eq!(dropped, 4);
    }

    #[test]
    fn no_extension_is_safe() {
        let refs = vec![("foo".into(), 1usize)];
        let (kept, dropped) = filter_refs(refs, Path::new("Makefile"));
        assert_eq!(kept.len(), 1);
        assert_eq!(dropped, 0);
    }
}
